DROP EXTENSION pg_net;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE TABLE public.artifacts_pub (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, owner text DEFAULT 'demo'::text, video_id text, t_s real, widget text, title text, spec jsonb NOT NULL, remixed_from bigint, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.artifacts_pub ADD CONSTRAINT artifacts_pub_pkey PRIMARY KEY (id);
GRANT ALL ON public.artifacts_pub TO anon;
GRANT ALL ON public.artifacts_pub TO authenticated;
GRANT ALL ON public.artifacts_pub TO service_role;
CREATE TABLE public.concepts (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, video_id text, t_s double precision, widget text, spec jsonb NOT NULL, model text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.concepts ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);
GRANT ALL ON public.concepts TO anon;
GRANT ALL ON public.concepts TO authenticated;
GRANT ALL ON public.concepts TO service_role;
CREATE INDEX concepts_video_idx ON public.concepts (video_id);
CREATE TABLE public.curriculum (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, goal_id bigint, seq integer NOT NULL, video_id text, concept_id bigint, rationale text, state text DEFAULT 'planned'::text, unit integer, lesson_title text);
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id);
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_goal_id_seq_key UNIQUE (goal_id, seq);
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_pkey PRIMARY KEY (id);
GRANT ALL ON public.curriculum TO anon;
GRANT ALL ON public.curriculum TO authenticated;
GRANT ALL ON public.curriculum TO service_role;
CREATE TABLE public.frames (video_id text NOT NULL, t_s double precision NOT NULL, storage_path text NOT NULL);
ALTER TABLE public.frames ADD CONSTRAINT frames_pkey PRIMARY KEY (video_id, t_s);
GRANT ALL ON public.frames TO anon;
GRANT ALL ON public.frames TO authenticated;
GRANT ALL ON public.frames TO service_role;
CREATE TABLE public.goals (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, user_id uuid, goal_text text NOT NULL, status text DEFAULT 'active'::text, created_at timestamp with time zone DEFAULT now(), kind text, level text, chosen_path_id bigint);
ALTER TABLE public.goals ADD CONSTRAINT goals_pkey PRIMARY KEY (id);
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;
GRANT ALL ON public.goals TO anon;
GRANT ALL ON public.goals TO authenticated;
GRANT ALL ON public.goals TO service_role;
CREATE TABLE public.inference_cache (cache_key text NOT NULL, video_id text, model text, prompt_hash text, result jsonb NOT NULL, hits integer DEFAULT 0, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.inference_cache ADD CONSTRAINT inference_cache_pkey PRIMARY KEY (cache_key);
GRANT ALL ON public.inference_cache TO anon;
GRANT ALL ON public.inference_cache TO authenticated;
GRANT ALL ON public.inference_cache TO service_role;
CREATE INDEX inference_cache_video_idx ON public.inference_cache (video_id);
CREATE TABLE public.learners (user_id uuid DEFAULT gen_random_uuid() NOT NULL, handle text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.learners ADD CONSTRAINT learners_pkey PRIMARY KEY (user_id);
ALTER TABLE public.goals ADD CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.learners(user_id) ON DELETE CASCADE;
GRANT ALL ON public.learners TO anon;
GRANT ALL ON public.learners TO authenticated;
GRANT ALL ON public.learners TO service_role;
CREATE TABLE public.mastery (user_id uuid NOT NULL, concept_key text NOT NULL, score double precision DEFAULT 0, last_review timestamp with time zone);
ALTER TABLE public.mastery ADD CONSTRAINT mastery_pkey PRIMARY KEY (user_id, concept_key);
ALTER TABLE public.mastery ADD CONSTRAINT mastery_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.learners(user_id) ON DELETE CASCADE;
GRANT ALL ON public.mastery TO anon;
GRANT ALL ON public.mastery TO authenticated;
GRANT ALL ON public.mastery TO service_role;
CREATE TABLE public.monitored_channels (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, user_id uuid, channel_id text NOT NULL, last_checked timestamp with time zone, last_video_id text);
ALTER TABLE public.monitored_channels ADD CONSTRAINT monitored_channels_pkey PRIMARY KEY (id);
ALTER TABLE public.monitored_channels ADD CONSTRAINT monitored_channels_user_id_channel_id_key UNIQUE (user_id, channel_id);
ALTER TABLE public.monitored_channels ADD CONSTRAINT monitored_channels_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.learners(user_id) ON DELETE CASCADE;
GRANT ALL ON public.monitored_channels TO anon;
GRANT ALL ON public.monitored_channels TO authenticated;
GRANT ALL ON public.monitored_channels TO service_role;
CREATE TABLE public.paths (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, goal_id bigint, label text NOT NULL, rationale text, video_ids text[] DEFAULT '{}'::text[] NOT NULL, est_minutes integer DEFAULT 0, auto boolean DEFAULT false, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.paths ADD CONSTRAINT paths_pkey PRIMARY KEY (id);
GRANT ALL ON public.paths TO anon;
GRANT ALL ON public.paths TO authenticated;
GRANT ALL ON public.paths TO service_role;
CREATE TABLE public.runs (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, user_id uuid, job text, woke_at timestamp with time zone DEFAULT now(), decided jsonb, actions jsonb, status text);
ALTER TABLE public.runs ADD CONSTRAINT runs_pkey PRIMARY KEY (id);
ALTER TABLE public.runs ADD CONSTRAINT runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.learners(user_id) ON DELETE SET NULL;
GRANT ALL ON public.runs TO anon;
GRANT ALL ON public.runs TO authenticated;
GRANT ALL ON public.runs TO service_role;
CREATE INDEX runs_time_idx ON public.runs (woke_at DESC);
CREATE TABLE public.transcripts (video_id text NOT NULL, cues jsonb DEFAULT '[]'::jsonb NOT NULL);
ALTER TABLE public.transcripts ADD CONSTRAINT transcripts_pkey PRIMARY KEY (video_id);
GRANT ALL ON public.transcripts TO anon;
GRANT ALL ON public.transcripts TO authenticated;
GRANT ALL ON public.transcripts TO service_role;
CREATE TABLE public.videos (video_id text NOT NULL, title text, channel_id text, channel_name text, duration_s double precision, chapters jsonb DEFAULT '[]'::jsonb, ingested_at timestamp with time zone DEFAULT now(), genre text);
ALTER TABLE public.videos ADD CONSTRAINT videos_pkey PRIMARY KEY (video_id);
ALTER TABLE public.concepts ADD CONSTRAINT concepts_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(video_id) ON DELETE CASCADE;
ALTER TABLE public.curriculum ADD CONSTRAINT curriculum_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(video_id);
ALTER TABLE public.frames ADD CONSTRAINT frames_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(video_id) ON DELETE CASCADE;
ALTER TABLE public.transcripts ADD CONSTRAINT transcripts_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(video_id) ON DELETE CASCADE;
GRANT ALL ON public.videos TO anon;
GRANT ALL ON public.videos TO authenticated;
GRANT ALL ON public.videos TO service_role;
CREATE TABLE public.votes (artifact_id bigint NOT NULL, voter text DEFAULT 'demo'::text NOT NULL, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.votes ADD CONSTRAINT votes_pkey PRIMARY KEY (artifact_id, voter);
GRANT ALL ON public.votes TO anon;
GRANT ALL ON public.votes TO authenticated;
GRANT ALL ON public.votes TO service_role;
